version: "3.10"

services:
  web:
    build: .
    command: python /bookstore/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/bookstore
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-whuaae0qt^v^*-+e56)e$$n^jqycsltg$$u1_j$$@%4)6!=%qe@b5"
      - "DJANGO_DEBUG=True"
      
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
  
