version: "3.10"

services:
  web:
    build: .
    command: python /postgres/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/postgres
    ports:
      - "8000:8000"
  db:
    image: postgres:14
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
